// <auto-generated>
//     このファイルは rclsharp-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/Byte
// </auto-generated>
using Rclsharp.Cdr;

namespace Rclsharp.Msgs.Std
{
    /// <summary>
    /// std_msgs/msg/Byte の C# 表現 (生成コード)。
    /// </summary>
    public struct ByteMessage
    {
        public const string RosTypeName = "std_msgs/msg/Byte";
        public const string DdsTypeName = "std_msgs::msg::dds_::Byte_";

        public byte Data;

        public ByteMessage(byte data)
        {
            Data = data;
        }

        public override string ToString() => $"ByteMessage(data={Data})";
    }

    public sealed class ByteMessageSerializer : ICdrSerializer<ByteMessage>
    {
        public static readonly ByteMessageSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in ByteMessage value)
        {
            int total = 0;
            total += 1;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in ByteMessage value)
        {
            writer.WriteByte(value.Data);
        }

        public void Deserialize(ref CdrReader reader, out ByteMessage value)
        {
            byte data = reader.ReadByte();
            value = new ByteMessage(data);
        }

        public void SerializeKey(ref CdrWriter writer, in ByteMessage value)
        {
        }
    }
}
