// <auto-generated>
//     このファイルは rclsharp-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/ByteMultiArray
// </auto-generated>
using Rclsharp.Cdr;

namespace Rclsharp.Msgs.Std
{
    /// <summary>
    /// std_msgs/msg/ByteMultiArray の C# 表現 (生成コード)。
    /// </summary>
    public struct ByteMultiArray
    {
        public const string RosTypeName = "std_msgs/msg/ByteMultiArray";
        public const string DdsTypeName = "std_msgs::msg::dds_::ByteMultiArray_";

        public MultiArrayLayout Layout;
        public byte[] Data;

        public ByteMultiArray(MultiArrayLayout layout, byte[] data)
        {
            Layout = layout;
            Data = data;
        }

        public override string ToString() => $"ByteMultiArray(layout={Layout}, data=[{(Data is null ? 0 : Data.Length)}])";
    }

    public sealed class ByteMultiArraySerializer : ICdrSerializer<ByteMultiArray>
    {
        public static readonly ByteMultiArraySerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in ByteMultiArray value)
        {
            int total = 0;
            total += MultiArrayLayoutSerializer.Instance.GetSerializedSize(in value.Layout);
            total += 3;
            total += 4;
            total += (value.Data is null ? 0 : value.Data.Length) * 1;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in ByteMultiArray value)
        {
            MultiArrayLayoutSerializer.Instance.Serialize(ref writer, in value.Layout);
            var arrData = value.Data ?? System.Array.Empty<byte>();
            writer.WriteSequenceLength(arrData.Length);
            writer.WriteRawBytes(arrData);
        }

        public void Deserialize(ref CdrReader reader, out ByteMultiArray value)
        {
            MultiArrayLayoutSerializer.Instance.Deserialize(ref reader, out MultiArrayLayout layout);
            int dataCount = reader.ReadSequenceLength(1, 1);
            var data = dataCount == 0 ? System.Array.Empty<byte>() : reader.ReadRawBytes(dataCount).ToArray();
            value = new ByteMultiArray(layout, data);
        }

        public void SerializeKey(ref CdrWriter writer, in ByteMultiArray value)
        {
        }
    }
}
