// <auto-generated>
//     このファイルは rclsharp-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/Empty
// </auto-generated>
using Rclsharp.Cdr;

namespace Rclsharp.Msgs.Std
{
    /// <summary>
    /// std_msgs/msg/Empty の C# 表現 (生成コード)。
    /// </summary>
    public struct EmptyMessage
    {
        public const string RosTypeName = "std_msgs/msg/Empty";
        public const string DdsTypeName = "std_msgs::msg::dds_::Empty_";

        public override string ToString() => "EmptyMessage()";
    }

    public sealed class EmptyMessageSerializer : ICdrSerializer<EmptyMessage>
    {
        public static readonly EmptyMessageSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in EmptyMessage value)
        {
            return 1;
        }

        public void Serialize(ref CdrWriter writer, in EmptyMessage value)
        {
            writer.WriteByte(0); // rosidl structure dummy
        }

        public void Deserialize(ref CdrReader reader, out EmptyMessage value)
        {
            _ = reader.ReadByte(); // rosidl structure dummy
            value = default;
        }

        public void SerializeKey(ref CdrWriter writer, in EmptyMessage value)
        {
        }
    }
}
