// <auto-generated>
//     このファイルは rclsharp-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/Float32MultiArray
// </auto-generated>
using Rclsharp.Cdr;

namespace Rclsharp.Msgs.Std
{
    /// <summary>
    /// std_msgs/msg/Float32MultiArray の C# 表現 (生成コード)。
    /// </summary>
    public struct Float32MultiArray
    {
        public const string RosTypeName = "std_msgs/msg/Float32MultiArray";
        public const string DdsTypeName = "std_msgs::msg::dds_::Float32MultiArray_";

        public MultiArrayLayout Layout;
        public float[] Data;

        public Float32MultiArray(MultiArrayLayout layout, float[] data)
        {
            Layout = layout;
            Data = data;
        }

        public override string ToString() => $"Float32MultiArray(layout={Layout}, data=[{(Data is null ? 0 : Data.Length)}])";
    }

    public sealed class Float32MultiArraySerializer : ICdrSerializer<Float32MultiArray>
    {
        public static readonly Float32MultiArraySerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Float32MultiArray value)
        {
            int total = 0;
            total += MultiArrayLayoutSerializer.Instance.GetSerializedSize(in value.Layout);
            total += 3;
            total += 4;
            total += (value.Data is null ? 0 : value.Data.Length) * 4;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Float32MultiArray value)
        {
            MultiArrayLayoutSerializer.Instance.Serialize(ref writer, in value.Layout);
            var arrData = value.Data ?? System.Array.Empty<float>();
            writer.WriteSequenceLength(arrData.Length);
            foreach (var eData in arrData)
            {
                writer.WriteFloat(eData);
            }
        }

        public void Deserialize(ref CdrReader reader, out Float32MultiArray value)
        {
            MultiArrayLayoutSerializer.Instance.Deserialize(ref reader, out MultiArrayLayout layout);
            int dataCount = reader.ReadSequenceLength(4, 4);
            var data = dataCount == 0 ? System.Array.Empty<float>() : new float[dataCount];
            for (int i = 0; i < dataCount; i++)
            {
                data[i] = reader.ReadFloat();
            }
            value = new Float32MultiArray(layout, data);
        }

        public void SerializeKey(ref CdrWriter writer, in Float32MultiArray value)
        {
        }
    }
}
