// <auto-generated>
//     このファイルは rclsharp-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/Int64
// </auto-generated>
using Rclsharp.Cdr;

namespace Rclsharp.Msgs.Std
{
    /// <summary>
    /// std_msgs/msg/Int64 の C# 表現 (生成コード)。
    /// </summary>
    public struct Int64Message
    {
        public const string RosTypeName = "std_msgs/msg/Int64";
        public const string DdsTypeName = "std_msgs::msg::dds_::Int64_";

        public long Data;

        public Int64Message(long data)
        {
            Data = data;
        }

        public override string ToString() => $"Int64Message(data={Data})";
    }

    public sealed class Int64MessageSerializer : ICdrSerializer<Int64Message>
    {
        public static readonly Int64MessageSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Int64Message value)
        {
            int total = 0;
            total += 8;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Int64Message value)
        {
            writer.WriteInt64(value.Data);
        }

        public void Deserialize(ref CdrReader reader, out Int64Message value)
        {
            long data = reader.ReadInt64();
            value = new Int64Message(data);
        }

        public void SerializeKey(ref CdrWriter writer, in Int64Message value)
        {
        }
    }
}
