// <auto-generated>
//     このファイルは rclsharp-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/Int8MultiArray
// </auto-generated>
using Rclsharp.Cdr;

namespace Rclsharp.Msgs.Std;

/// <summary>
/// std_msgs/msg/Int8MultiArray の C# 表現 (生成コード)。
/// </summary>
public struct Int8MultiArray
{
    public const string RosTypeName = "std_msgs/msg/Int8MultiArray";
    public const string DdsTypeName = "std_msgs::msg::dds_::Int8MultiArray_";

    public MultiArrayLayout Layout;
    public sbyte[] Data;

    public Int8MultiArray(MultiArrayLayout layout, sbyte[] data)
    {
        Layout = layout;
        Data = data;
    }

    public override string ToString() => $"Int8MultiArray(layout={Layout}, data=[{(Data is null ? 0 : Data.Length)}])";
}

public sealed class Int8MultiArraySerializer : ICdrSerializer<Int8MultiArray>
{
    public static readonly Int8MultiArraySerializer Instance = new();

    public bool IsKeyed => false;

    public int GetSerializedSize(in Int8MultiArray value)
    {
        int total = 0;
        total += MultiArrayLayoutSerializer.Instance.GetSerializedSize(in value.Layout);
        total += 3;
        total += 4;
        total += (value.Data is null ? 0 : value.Data.Length) * 1;
        return total;
    }

    public void Serialize(ref CdrWriter writer, in Int8MultiArray value)
    {
        MultiArrayLayoutSerializer.Instance.Serialize(ref writer, in value.Layout);
        var arrData = value.Data ?? System.Array.Empty<sbyte>();
        writer.WriteSequenceLength(arrData.Length);
        foreach (var eData in arrData)
        {
            writer.WriteSByte(eData);
        }
    }

    public void Deserialize(ref CdrReader reader, out Int8MultiArray value)
    {
        MultiArrayLayoutSerializer.Instance.Deserialize(ref reader, out MultiArrayLayout layout);
        int dataCount = reader.ReadSequenceLength(1, 1);
        var data = dataCount == 0 ? System.Array.Empty<sbyte>() : new sbyte[dataCount];
        for (int i = 0; i < dataCount; i++)
        {
            data[i] = reader.ReadSByte();
        }
        value = new Int8MultiArray(layout, data);
    }

    public void SerializeKey(ref CdrWriter writer, in Int8MultiArray value)
    {
    }
}
