// <auto-generated>
//     このファイルは rclsharp-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/UInt8MultiArray
// </auto-generated>
using Rclsharp.Cdr;

namespace Rclsharp.Msgs.Std
{
    /// <summary>
    /// std_msgs/msg/UInt8MultiArray の C# 表現 (生成コード)。
    /// </summary>
    public struct UInt8MultiArray
    {
        public const string RosTypeName = "std_msgs/msg/UInt8MultiArray";
        public const string DdsTypeName = "std_msgs::msg::dds_::UInt8MultiArray_";

        public MultiArrayLayout Layout;
        public byte[] Data;

        public UInt8MultiArray(MultiArrayLayout layout, byte[] data)
        {
            Layout = layout;
            Data = data;
        }

        public override string ToString() => $"UInt8MultiArray(layout={Layout}, data=[{(Data is null ? 0 : Data.Length)}])";
    }

    public sealed class UInt8MultiArraySerializer : ICdrSerializer<UInt8MultiArray>
    {
        public static readonly UInt8MultiArraySerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in UInt8MultiArray value)
        {
            int total = 0;
            total += MultiArrayLayoutSerializer.Instance.GetSerializedSize(in value.Layout);
            total += 3;
            total += 4;
            total += (value.Data is null ? 0 : value.Data.Length) * 1;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in UInt8MultiArray value)
        {
            MultiArrayLayoutSerializer.Instance.Serialize(ref writer, in value.Layout);
            var arrData = value.Data ?? System.Array.Empty<byte>();
            writer.WriteSequenceLength(arrData.Length);
            foreach (var eData in arrData)
            {
                writer.WriteByte(eData);
            }
        }

        public void Deserialize(ref CdrReader reader, out UInt8MultiArray value)
        {
            MultiArrayLayoutSerializer.Instance.Deserialize(ref reader, out MultiArrayLayout layout);
            int dataCount = reader.ReadSequenceLength(1, 1);
            var data = dataCount == 0 ? System.Array.Empty<byte>() : new byte[dataCount];
            for (int i = 0; i < dataCount; i++)
            {
                data[i] = reader.ReadByte();
            }
            value = new UInt8MultiArray(layout, data);
        }

        public void SerializeKey(ref CdrWriter writer, in UInt8MultiArray value)
        {
        }
    }
}
