// <auto-generated>
//     このファイルは rclsharp-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/UInt8
// </auto-generated>
using Rclsharp.Cdr;

namespace Rclsharp.Msgs.Std
{
    /// <summary>
    /// std_msgs/msg/UInt8 の C# 表現 (生成コード)。
    /// </summary>
    public struct UInt8Message
    {
        public const string RosTypeName = "std_msgs/msg/UInt8";
        public const string DdsTypeName = "std_msgs::msg::dds_::UInt8_";

        public byte Data;

        public UInt8Message(byte data)
        {
            Data = data;
        }

        public override string ToString() => $"UInt8Message(data={Data})";
    }

    public sealed class UInt8MessageSerializer : ICdrSerializer<UInt8Message>
    {
        public static readonly UInt8MessageSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in UInt8Message value)
        {
            int total = 0;
            total += 1;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in UInt8Message value)
        {
            writer.WriteByte(value.Data);
        }

        public void Deserialize(ref CdrReader reader, out UInt8Message value)
        {
            byte data = reader.ReadByte();
            value = new UInt8Message(data);
        }

        public void SerializeKey(ref CdrWriter writer, in UInt8Message value)
        {
        }
    }
}
