using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Rclsharp.MsgGen.Model;
using Rclsharp.MsgGen.TypeMapping;

namespace Rclsharp.MsgGen.Emitting;

/// <summary>
/// <see cref="MessageDefinition"/> を、既存手書き <c>Rclsharp.Msgs.*</c> と CDR 互換な C# ソースへ変換する。
/// 生成物は <c>struct</c> と <c>ICdrSerializer&lt;T&gt;</c> 実装のペア。
/// </summary>
public sealed class CSharpEmitter
{
    private readonly TypeNameResolver _resolver;
    private readonly TypeMetrics _metrics;

    public CSharpEmitter(TypeNameResolver? resolver = null, MessageRegistry? registry = null)
    {
        _resolver = resolver ?? new TypeNameResolver();
        _metrics = new TypeMetrics(registry ?? new MessageRegistry());
    }

    /// <summary>1 つの msg 定義を 1 ファイル分の C# ソースに変換する。</summary>
    public string Emit(MessageDefinition def)
    {
        string ns = _resolver.Namespace(def.Package);
        string typeName = _resolver.CSharpTypeName(def.Package, def.Name);
        string serializerName = _resolver.SerializerName(def.Package, def.Name);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//     このファイルは rclsharp-genmsg により生成されました。手動で編集しないでください。\n");
        sb.Append($"//     source: {def.RosTypeName}\n");
        sb.Append("// </auto-generated>\n");

        sb.Append("using Rclsharp.Cdr;\n");
        foreach (string u in CollectUsings(def, ns))
        {
            sb.Append($"using {u};\n");
        }
        sb.Append('\n');
        sb.Append($"namespace {ns};\n\n");

        EmitStruct(sb, def, typeName);
        sb.Append('\n');
        EmitSerializer(sb, def, typeName, serializerName);

        return sb.ToString();
    }

    private IEnumerable<string> CollectUsings(MessageDefinition def, string ownNamespace)
    {
        var set = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var f in def.Fields)
        {
            if (f.Type.Category != BaseTypeCategory.Named) continue;
            string pkg = f.Type.Package ?? def.Package;
            string ns = _resolver.Namespace(pkg);
            if (ns != ownNamespace) set.Add(ns);
        }
        return set;
    }

    // ----- struct -----

    private void EmitStruct(StringBuilder sb, MessageDefinition def, string typeName)
    {
        sb.Append("/// <summary>\n");
        sb.Append($"/// {def.RosTypeName} の C# 表現 (生成コード)。\n");
        sb.Append("/// </summary>\n");
        sb.Append($"public struct {typeName}\n{{\n");

        sb.Append($"    public const string RosTypeName = \"{_resolver.RosTypeName(def.Package, def.Name)}\";\n");
        sb.Append($"    public const string DdsTypeName = \"{_resolver.DdsTypeName(def.Package, def.Name)}\";\n");

        // 定数
        if (def.Constants.Count > 0)
        {
            sb.Append('\n');
            foreach (var c in def.Constants)
            {
                string cty = CSharpType(c.Type, def.Package);
                sb.Append($"    public const {cty} {c.Name} = {FormatConstant(c)};\n");
            }
        }

        // フィールド
        bool anyDefault = def.Fields.Any(f => f.DefaultValue != null);
        if (def.Fields.Count > 0)
        {
            sb.Append('\n');
            foreach (var f in def.Fields)
            {
                string fty = CSharpType(f.Type, def.Package);
                string fname = NamingConventions.ToPascalCase(f.Name);
                string? init = f.DefaultValue != null ? FormatFieldDefault(f, def.Package) : null;
                sb.Append(init != null ? $"    public {fty} {fname} = {init};\n" : $"    public {fty} {fname};\n");
            }
        }

        // コンストラクタ
        if (def.Fields.Count > 0)
        {
            if (anyDefault)
            {
                sb.Append($"\n    public {typeName}()\n    {{\n    }}\n");
            }

            string ctorParams = string.Join(", ", def.Fields.Select(f =>
                $"{CSharpType(f.Type, def.Package)} {NamingConventions.ToCamelCase(f.Name)}"));
            sb.Append($"\n    public {typeName}({ctorParams})\n    {{\n");
            foreach (var f in def.Fields)
            {
                sb.Append($"        {NamingConventions.ToPascalCase(f.Name)} = {NamingConventions.ToCamelCase(f.Name)};\n");
            }
            sb.Append("    }\n");
        }

        EmitToString(sb, def, typeName);
        sb.Append("}\n");
    }

    private void EmitToString(StringBuilder sb, MessageDefinition def, string typeName)
    {
        sb.Append('\n');
        if (def.Fields.Count == 0)
        {
            sb.Append($"    public override string ToString() => \"{typeName}()\";\n");
            return;
        }
        var parts = def.Fields.Select(f =>
        {
            string pname = NamingConventions.ToPascalCase(f.Name);
            if (f.Type.IsArray)
            {
                return $"{f.Name}=[{{({pname} is null ? 0 : {pname}.Length)}}]";
            }
            return $"{f.Name}={{{pname}}}";
        });
        sb.Append($"    public override string ToString() => $\"{typeName}({string.Join(", ", parts)})\";\n");
    }

    // ----- serializer -----

    private void EmitSerializer(StringBuilder sb, MessageDefinition def, string typeName, string serializerName)
    {
        sb.Append($"public sealed class {serializerName} : ICdrSerializer<{typeName}>\n{{\n");
        sb.Append($"    public static readonly {serializerName} Instance = new();\n\n");
        sb.Append("    public bool IsKeyed => false;\n\n");

        EmitGetSerializedSize(sb, def, typeName);
        sb.Append('\n');
        EmitSerialize(sb, def, typeName);
        sb.Append('\n');
        EmitDeserialize(sb, def, typeName);
        sb.Append('\n');
        sb.Append($"    public void SerializeKey(ref CdrWriter writer, in {typeName} value)\n    {{\n    }}\n");

        sb.Append("}\n");
    }

    private void EmitGetSerializedSize(StringBuilder sb, MessageDefinition def, string typeName)
    {
        sb.Append($"    public int GetSerializedSize(in {typeName} value)\n    {{\n");
        if (def.Fields.Count == 0)
        {
            // rosidl の空メッセージは 1 バイトの structure dummy を持つ。
            sb.Append("        return 1;\n    }\n");
            return;
        }

        sb.Append("        int total = 0;\n");

        // CDR の整列パディングを静的に追跡する。位置が確定している間は正確な pad を、
        // 可変長フィールド以降は後続の整列上限 (align-1) を安全側で見込む。
        bool positionKnown = true;
        int knownOffset = 0;
        foreach (var f in def.Fields)
        {
            string pname = NamingConventions.ToPascalCase(f.Name);
            SizeInfo fi = _metrics.OfField(f.Type, def.Package);
            int la = fi.LeadingAlignment;

            if (positionKnown)
            {
                int pad = TypeMetrics.Align(knownOffset, la) - knownOffset;
                if (pad > 0)
                {
                    sb.Append($"        total += {pad};\n");
                    knownOffset += pad;
                }
            }
            else if (la > 1)
            {
                sb.Append($"        total += {la - 1};\n");
            }

            EmitSizeContribution(sb, f, pname, def.Package);

            if (positionKnown && fi.IsFixed)
            {
                knownOffset += fi.FixedSize;
            }
            else if (!fi.IsFixed)
            {
                positionKnown = false;
            }
        }
        sb.Append("        return total;\n    }\n");
    }

    private void EmitSizeContribution(StringBuilder sb, MessageField f, string pname, string ownPkg)
    {
        var t = f.Type;
        if (!t.IsArray)
        {
            switch (t.Category)
            {
                case BaseTypeCategory.Primitive:
                    sb.Append($"        total += {PrimitiveTypes.Get(t.PrimitiveName!).Size};\n");
                    return;
                case BaseTypeCategory.String:
                    sb.Append($"        int {LenLocal(pname)} = value.{pname} is null ? 0 : System.Text.Encoding.UTF8.GetByteCount(value.{pname});\n");
                    sb.Append($"        total += 4 + {LenLocal(pname)} + 1;\n");
                    return;
                case BaseTypeCategory.Named:
                    sb.Append($"        total += {SerializerRef(t, ownPkg)}.Instance.GetSerializedSize(in value.{pname});\n");
                    return;
            }
        }

        // 配列
        bool fixedSize = t.ArrayKind == ArrayKind.FixedSize;
        if (!fixedSize)
        {
            sb.Append("        total += 4;\n"); // sequence length
        }

        switch (t.Category)
        {
            case BaseTypeCategory.Primitive:
                int sz = PrimitiveTypes.Get(t.PrimitiveName!).Size;
                if (fixedSize)
                {
                    sb.Append($"        total += {t.ArrayLength} * {sz};\n");
                }
                else
                {
                    sb.Append($"        total += (value.{pname} is null ? 0 : value.{pname}.Length) * {sz};\n");
                }
                return;
            case BaseTypeCategory.String:
                sb.Append($"        if (value.{pname} is not null)\n");
                sb.Append($"        {{\n");
                sb.Append($"            foreach (var {ElemLocal(pname)} in value.{pname})\n");
                sb.Append($"            {{\n");
                sb.Append($"                total += 4 + ({ElemLocal(pname)} is null ? 0 : System.Text.Encoding.UTF8.GetByteCount({ElemLocal(pname)})) + 1;\n");
                sb.Append($"            }}\n");
                sb.Append($"        }}\n");
                return;
            case BaseTypeCategory.Named:
                sb.Append($"        if (value.{pname} is not null)\n");
                sb.Append($"        {{\n");
                sb.Append($"            var {SerLocal(pname)} = {SerializerRef(t, ownPkg)}.Instance;\n");
                sb.Append($"            foreach (ref readonly var {ElemLocal(pname)} in value.{pname}.AsSpan())\n");
                sb.Append($"            {{\n");
                sb.Append($"                total += {SerLocal(pname)}.GetSerializedSize(in {ElemLocal(pname)});\n");
                sb.Append($"            }}\n");
                sb.Append($"        }}\n");
                return;
        }
    }

    private void EmitSerialize(StringBuilder sb, MessageDefinition def, string typeName)
    {
        sb.Append($"    public void Serialize(ref CdrWriter writer, in {typeName} value)\n    {{\n");
        if (def.Fields.Count == 0)
        {
            sb.Append("        writer.WriteByte(0); // rosidl structure dummy\n    }\n");
            return;
        }
        foreach (var f in def.Fields)
        {
            EmitSerializeField(sb, f, NamingConventions.ToPascalCase(f.Name), def.Package);
        }
        sb.Append("    }\n");
    }

    private void EmitSerializeField(StringBuilder sb, MessageField f, string pname, string ownPkg)
    {
        var t = f.Type;
        if (!t.IsArray)
        {
            switch (t.Category)
            {
                case BaseTypeCategory.Primitive:
                    sb.Append($"        writer.{PrimitiveTypes.Get(t.PrimitiveName!).WriteMethod}(value.{pname});\n");
                    return;
                case BaseTypeCategory.String:
                    sb.Append($"        writer.WriteString(value.{pname});\n");
                    return;
                case BaseTypeCategory.Named:
                    sb.Append($"        {SerializerRef(t, ownPkg)}.Instance.Serialize(ref writer, in value.{pname});\n");
                    return;
            }
        }

        string elem = ElementCSharpType(t, ownPkg);
        bool fixedSize = t.ArrayKind == ArrayKind.FixedSize;
        string arrExpr;
        if (fixedSize)
        {
            // 固定長配列は常に N 要素。null の場合はゼロ初期化配列で代替し NRE を避ける。
            sb.Append($"        var {LocalArr(pname)} = value.{pname} ?? new {elem}[{t.ArrayLength}];\n");
            arrExpr = LocalArr(pname);
        }
        else
        {
            sb.Append($"        var {LocalArr(pname)} = value.{pname} ?? System.Array.Empty<{elem}>();\n");
            sb.Append($"        writer.WriteSequenceLength({LocalArr(pname)}.Length);\n");
            arrExpr = LocalArr(pname);
        }

        // byte[] の可変長は raw bytes でまとめて書く (既存 ByteMultiArray 互換)。
        if (!fixedSize && t.Category == BaseTypeCategory.Primitive && t.PrimitiveName == "byte")
        {
            sb.Append($"        writer.WriteRawBytes({arrExpr});\n");
            return;
        }

        int count = fixedSize ? t.ArrayLength : -1;
        string loopHeader = fixedSize
            ? $"        for (int i = 0; i < {count}; i++)\n        {{\n"
            : $"        foreach (var {ElemLocal(pname)} in {arrExpr})\n        {{\n";
        string elemAccess = fixedSize ? $"{arrExpr}[i]" : ElemLocal(pname);

        sb.Append(loopHeader);
        switch (t.Category)
        {
            case BaseTypeCategory.Primitive:
                sb.Append($"            writer.{PrimitiveTypes.Get(t.PrimitiveName!).WriteMethod}({elemAccess});\n");
                break;
            case BaseTypeCategory.String:
                sb.Append($"            writer.WriteString({elemAccess});\n");
                break;
            case BaseTypeCategory.Named:
                sb.Append($"            {SerializerRef(t, ownPkg)}.Instance.Serialize(ref writer, in {elemAccess});\n");
                break;
        }
        sb.Append("        }\n");
    }

    private void EmitDeserialize(StringBuilder sb, MessageDefinition def, string typeName)
    {
        sb.Append($"    public void Deserialize(ref CdrReader reader, out {typeName} value)\n    {{\n");
        if (def.Fields.Count == 0)
        {
            sb.Append("        _ = reader.ReadByte(); // rosidl structure dummy\n");
            sb.Append("        value = default;\n    }\n");
            return;
        }

        var locals = new List<string>();
        foreach (var f in def.Fields)
        {
            string pname = NamingConventions.ToPascalCase(f.Name);
            string local = NamingConventions.ToCamelCase(f.Name);
            locals.Add(local);
            EmitDeserializeField(sb, f, local, def.Package);
        }
        sb.Append($"        value = new {typeName}({string.Join(", ", locals)});\n");
        sb.Append("    }\n");
    }

    private void EmitDeserializeField(StringBuilder sb, MessageField f, string local, string ownPkg)
    {
        var t = f.Type;
        if (!t.IsArray)
        {
            switch (t.Category)
            {
                case BaseTypeCategory.Primitive:
                    sb.Append($"        {CSharpType(t, ownPkg)} {local} = reader.{PrimitiveTypes.Get(t.PrimitiveName!).ReadMethod}();\n");
                    return;
                case BaseTypeCategory.String:
                    sb.Append($"        string {local} = reader.ReadString();\n");
                    return;
                case BaseTypeCategory.Named:
                    sb.Append($"        {SerializerRef(t, ownPkg)}.Instance.Deserialize(ref reader, out {ElementCSharpType(t, ownPkg)} {local});\n");
                    return;
            }
        }

        string elem = ElementCSharpType(t, ownPkg);
        bool fixedSize = t.ArrayKind == ArrayKind.FixedSize;
        string countExpr;
        if (fixedSize)
        {
            countExpr = t.ArrayLength.ToString();
            sb.Append($"        var {local} = new {elem}[{t.ArrayLength}];\n");
        }
        else
        {
            string seqLen = t.Category == BaseTypeCategory.Primitive
                ? $"reader.ReadSequenceLength({PrimitiveTypes.Get(t.PrimitiveName!).Size}, {PrimitiveTypes.Get(t.PrimitiveName!).Size})"
                : "reader.ReadSequenceLength()";
            sb.Append($"        int {local}Count = {seqLen};\n");
            countExpr = $"{local}Count";

            // byte[] は raw bytes でまとめて読む (既存 ByteMultiArray 互換)。
            if (t.Category == BaseTypeCategory.Primitive && t.PrimitiveName == "byte")
            {
                sb.Append($"        var {local} = {local}Count == 0 ? System.Array.Empty<byte>() : reader.ReadRawBytes({local}Count).ToArray();\n");
                return;
            }

            sb.Append($"        var {local} = {local}Count == 0 ? System.Array.Empty<{elem}>() : new {elem}[{local}Count];\n");
        }

        sb.Append($"        for (int i = 0; i < {countExpr}; i++)\n        {{\n");
        switch (t.Category)
        {
            case BaseTypeCategory.Primitive:
                sb.Append($"            {local}[i] = reader.{PrimitiveTypes.Get(t.PrimitiveName!).ReadMethod}();\n");
                break;
            case BaseTypeCategory.String:
                sb.Append($"            {local}[i] = reader.ReadString();\n");
                break;
            case BaseTypeCategory.Named:
                sb.Append($"            {SerializerRef(t, ownPkg)}.Instance.Deserialize(ref reader, out {local}[i]);\n");
                break;
        }
        sb.Append("        }\n");
    }

    // ----- helpers -----

    /// <summary>フィールド型を C# 型表記にする (配列なら <c>[]</c> 付き)。</summary>
    private string CSharpType(FieldType t, string ownPkg)
    {
        string elem = ElementCSharpType(t, ownPkg);
        return t.IsArray ? elem + "[]" : elem;
    }

    /// <summary>要素 (非配列) としての C# 型名。</summary>
    private string ElementCSharpType(FieldType t, string ownPkg)
    {
        switch (t.Category)
        {
            case BaseTypeCategory.Primitive:
                return PrimitiveTypes.Get(t.PrimitiveName!).CSharpType;
            case BaseTypeCategory.String:
                return "string";
            case BaseTypeCategory.Named:
                string pkg = t.Package ?? ownPkg;
                return _resolver.CSharpTypeName(pkg, t.Name!);
            default:
                throw new InvalidOperationException();
        }
    }

    private string SerializerRef(FieldType t, string ownPkg)
    {
        string pkg = t.Package ?? ownPkg;
        return _resolver.SerializerName(pkg, t.Name!);
    }

    private static string LenLocal(string pname) => "len" + pname;
    private static string ElemLocal(string pname) => "e" + pname;
    private static string SerLocal(string pname) => "ser" + pname;
    private static string LocalArr(string pname) => "arr" + pname;

    private string FormatConstant(MessageConstant c)
    {
        return FormatLiteral(c.Type, c.Value);
    }

    private string FormatFieldDefault(MessageField f, string ownPkg)
    {
        return FormatLiteral(f.Type, f.DefaultValue!);
    }

    /// <summary>定数/デフォルト値リテラルを C# 表現に整える (best-effort)。</summary>
    private string FormatLiteral(FieldType t, string raw)
    {
        raw = raw.Trim();
        if (t.Category == BaseTypeCategory.String)
        {
            if (raw.Length >= 2 && (raw[0] == '"' || raw[0] == '\'') && raw[raw.Length - 1] == raw[0])
            {
                raw = raw.Substring(1, raw.Length - 2);
            }
            return "\"" + raw.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        }
        if (t.Category == BaseTypeCategory.Primitive)
        {
            string p = t.PrimitiveName!;
            if (p == "bool")
            {
                return raw is "1" or "true" or "True" ? "true" : "false";
            }
            if (p == "float32" && !raw.EndsWith("f", StringComparison.OrdinalIgnoreCase))
            {
                return raw + "f";
            }
            // int の既定型は int。範囲外の値でもリテラル型を確定させるためサフィックスを付ける。
            if (IsIntegerLiteral(raw))
            {
                if (p == "uint64") return raw + "UL";
                if (p == "int64") return raw + "L";
                if (p == "uint32") return raw + "U";
            }
        }
        return raw;
    }

    private static bool IsIntegerLiteral(string s)
    {
        int start = s.Length > 0 && (s[0] == '+' || s[0] == '-') ? 1 : 0;
        if (start >= s.Length) return false;
        for (int i = start; i < s.Length; i++)
        {
            if (!char.IsDigit(s[i])) return false;
        }
        return true;
    }
}
