# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "commander-14.0.3" = {
      name = "commander";
      packageName = "commander";
      version = "14.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-14.0.3.tgz";
        sha512 = "H+y0Jo/T1RZ9qPP4Eh1pkcQcLRglraJaSLoyOtHxu6AapkjWVCy2Sit1QQ4x3Dng8qDlSsZEet7g5Pq06MvTgw==";
      };
    };
    "launch-unity-0.17.1" = {
      name = "launch-unity";
      packageName = "launch-unity";
      version = "0.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/launch-unity/-/launch-unity-0.17.1.tgz";
        sha512 = "Cfb2jgdkz/4K7AN/J9fYyzdVTKDavXzTRTNUEjSAriKyqsLyNkz0g/6SA475jIjjGyaZj50m/CFcU+ZK5rgmlg==";
      };
    };
    "semver-7.8.0" = {
      name = "semver";
      packageName = "semver";
      version = "7.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.8.0.tgz";
        sha512 = "AcM7dV/5ul4EekoQ29Agm5vri8JNqRyj39o0qpX6vDF2GZrtutZl5RwgD1XnZjiTAfncsJhMI48QQH3sN87YNA==";
      };
    };
  };
in
{
  "uloop-cli-2.1.3" = nodeEnv.buildNodePackage {
    name = "uloop-cli";
    packageName = "uloop-cli";
    version = "2.1.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/uloop-cli/-/uloop-cli-2.1.3.tgz";
      sha512 = "iFbBkT0nKJIE7UgJq1Jakj4o8Zug3HE4ABd6g6itbgMwh4O2HyUSltEWmbaXkhclCD6fTOTVxWzlVfmNBCOn1g==";
    };
    dependencies = [
      sources."commander-14.0.3"
      sources."launch-unity-0.17.1"
      sources."semver-7.8.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "CLI tool for Unity Editor communication via uLoopMCP";
      homepage = "https://github.com/hatayama/uLoopMCP#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
