// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/Float32
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Std
{
    /// <summary>
    /// std_msgs/msg/Float32 の C# 表現 (生成コード)。
    /// </summary>
    public struct Float32Message
    {
        public const string RosTypeName = "std_msgs/msg/Float32";
        public const string DdsTypeName = "std_msgs::msg::dds_::Float32_";

        public float Data;

        public Float32Message(float data)
        {
            Data = data;
        }

        public override string ToString() => $"Float32Message(data={Data})";
    }

    public sealed class Float32MessageSerializer : ICdrSerializer<Float32Message>
    {
        public static readonly Float32MessageSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Float32Message value)
        {
            int total = 0;
            total += 4;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Float32Message value)
        {
            writer.WriteFloat(value.Data);
        }

        public void Deserialize(ref CdrReader reader, out Float32Message value)
        {
            float data = reader.ReadFloat();
            value = new Float32Message(data);
        }

        public void SerializeKey(ref CdrWriter writer, in Float32Message value)
        {
        }
    }
}
