// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/Int16MultiArray
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Std
{
    /// <summary>
    /// std_msgs/msg/Int16MultiArray の C# 表現 (生成コード)。
    /// </summary>
    public struct Int16MultiArray
    {
        public const string RosTypeName = "std_msgs/msg/Int16MultiArray";
        public const string DdsTypeName = "std_msgs::msg::dds_::Int16MultiArray_";

        public MultiArrayLayout Layout;
        public short[] Data;

        public Int16MultiArray(MultiArrayLayout layout, short[] data)
        {
            Layout = layout;
            Data = data;
        }

        public override string ToString() => $"Int16MultiArray(layout={Layout}, data=[{(Data is null ? 0 : Data.Length)}])";
    }

    public sealed class Int16MultiArraySerializer : ICdrSerializer<Int16MultiArray>
    {
        public static readonly Int16MultiArraySerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Int16MultiArray value)
        {
            int total = 0;
            total += MultiArrayLayoutSerializer.Instance.GetSerializedSize(in value.Layout);
            total += 3;
            total += 4;
            total += (value.Data is null ? 0 : value.Data.Length) * 2;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Int16MultiArray value)
        {
            MultiArrayLayoutSerializer.Instance.Serialize(ref writer, in value.Layout);
            var arrData = value.Data ?? System.Array.Empty<short>();
            writer.WriteSequenceLength(arrData.Length);
            foreach (var eData in arrData)
            {
                writer.WriteInt16(eData);
            }
        }

        public void Deserialize(ref CdrReader reader, out Int16MultiArray value)
        {
            MultiArrayLayoutSerializer.Instance.Deserialize(ref reader, out MultiArrayLayout layout);
            int dataCount = reader.ReadSequenceLength(2, 2);
            var data = dataCount == 0 ? System.Array.Empty<short>() : new short[dataCount];
            for (int i = 0; i < dataCount; i++)
            {
                data[i] = reader.ReadInt16();
            }
            value = new Int16MultiArray(layout, data);
        }

        public void SerializeKey(ref CdrWriter writer, in Int16MultiArray value)
        {
        }
    }
}
