// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/Int16
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Std
{
    /// <summary>
    /// std_msgs/msg/Int16 の C# 表現 (生成コード)。
    /// </summary>
    public struct Int16Message
    {
        public const string RosTypeName = "std_msgs/msg/Int16";
        public const string DdsTypeName = "std_msgs::msg::dds_::Int16_";

        public short Data;

        public Int16Message(short data)
        {
            Data = data;
        }

        public override string ToString() => $"Int16Message(data={Data})";
    }

    public sealed class Int16MessageSerializer : ICdrSerializer<Int16Message>
    {
        public static readonly Int16MessageSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Int16Message value)
        {
            int total = 0;
            total += 2;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Int16Message value)
        {
            writer.WriteInt16(value.Data);
        }

        public void Deserialize(ref CdrReader reader, out Int16Message value)
        {
            short data = reader.ReadInt16();
            value = new Int16Message(data);
        }

        public void SerializeKey(ref CdrWriter writer, in Int16Message value)
        {
        }
    }
}
