// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/UInt16
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Std
{
    /// <summary>
    /// std_msgs/msg/UInt16 の C# 表現 (生成コード)。
    /// </summary>
    public struct UInt16Message
    {
        public const string RosTypeName = "std_msgs/msg/UInt16";
        public const string DdsTypeName = "std_msgs::msg::dds_::UInt16_";

        public ushort Data;

        public UInt16Message(ushort data)
        {
            Data = data;
        }

        public override string ToString() => $"UInt16Message(data={Data})";
    }

    public sealed class UInt16MessageSerializer : ICdrSerializer<UInt16Message>
    {
        public static readonly UInt16MessageSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in UInt16Message value)
        {
            int total = 0;
            total += 2;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in UInt16Message value)
        {
            writer.WriteUInt16(value.Data);
        }

        public void Deserialize(ref CdrReader reader, out UInt16Message value)
        {
            ushort data = reader.ReadUInt16();
            value = new UInt16Message(data);
        }

        public void SerializeKey(ref CdrWriter writer, in UInt16Message value)
        {
        }
    }
}
